### ISSUE TITLE
Trouble with author order file?

### ISSUE THREAD

**Issue by kadrlica** [DarkEnergySurvey/mkauthlist#1]
@pmelchior has mentioned some problems with the author ordering file.

From our conversation:

> PM: Something isn't quite right with ordering of some of the names in the order list:
>
> P. Melchior1⋆, D. Gruen2,3†, T. McClintock4, T. N. Varga5,6, E. Sheldon7, E. Rozo4, A. Amara8,
> M. R. Becker9,2, B. A. Benson10,11, A. Bermeo12, S. L. Bridle13, J. Clampitt14, J. P. 
> Dietrich15,16, W. G. Hartley17,8, D. Hollowood18, B. Jain14, M. Jarvis14, T. Jeltema18, T. 
> Kacprzak8, N. MacCrann13, E. S. Rykoff2,3, A. Saro16, E. Suchyta19, M. A. Troxel20,21, J. 
> Zuntz13, C. Bonnett22, A. A. Plazas23,
>
> Look at the end: Bonnett and Plazas should have been part of the 2nd tier authors but somehow ended up at the end between the properly ordered other authors and the builders. I didn't realize that, so we have it in the current version on arxiv.

> ADW: I think this is a "feature" rather than a bug. From looking at the author list here:
> http://dbweb5.fnal.gov:8080/DESPub/app/PB/pub/show_publication?pubid=148
> I see that both Bonnett and Plazas are in Tier 1 of the author list. The way the ordering works is to move the authors specified to the front of the list. It specifically does not re-order authors that are not specified. So a list that starts with:
> - Tier 1
> - Tier 2
>
> will go to:
>
> - Ordered Authors
> - Remaining Tier 1
> - Remaining Tier 2
>
> To get the behavior that you want, what you would do is use the '-s' or  '--sort' flag. This would perform the operation of first sorting the entire author list alphabetically before applying the author order file. Clearly this is something that needs better documentation (see item 1 above)

> PM: I don't think this is the whole story. I attached my order file, so you can see that I ordered Tier 1 and Tier 2 myself, and only expected the script to order the rest. But Bonnet and Plazas have been moved from the position in the Tier 2 list to the end of that list. That's not the expected behavior, is it?
>
> P. Melchior1⋆, D. Gruen2,3†, T. McClintock4, T. N. Varga5,6, E. Sheldon7, E. Rozo4, A. Amara8,
M. R. Becker9,2, B. A. Benson10,11, A. Bermeo12, S. L. Bridle13, J. Clampitt14, J. P. Dietrich15,16,
W. G. Hartley17,8, D. Hollowood18, B. Jain14, M. Jarvis14, T. Jeltema18, T. Kacprzak8, N. MacCrann13, E. S. Rykoff2,3, A. Saro16, E. Suchyta19, M. A. Troxel20,21, J. Zuntz13, C. Bonnett22, A. A. Plazas23,
>
> Let me know if I'm wrong or how I can fix it.

[order.txt](https://github.com/DarkEnergySurvey/mkauthlist/files/598154/order.txt)

**Comment by kadrlica** [comment]
@pmelchior I think the problem is with your `order.txt` file. 

When I run with `DES-2015-0148_author_list.csv` and `order.txt`, I get the following warnings:
```
python -i ./bin/mkauthlist -j mnras DES-2015-0148_author_list.csv -a order.txt 
% WARNING: Hacking umlaut escape sequence
% WARNING: Auxiliary name Bonnet not found
% WARNING: Auxiliary name Plazas not found
% WARNING: Blank affiliation for 'D.~Hollowood'
% WARNING: Blank affiliation for 'T.~Jeltema'
% WARNING: Blank affiliation for 'J.~Zuntz'
% WARNING: Blank affiliation for 'J.~Garc\'ia-Bellido'
```

* The first one is a warning about double quoted umlauts and can be ignored.
* The next one is a typo in Christopher's name.
* The third one is happening because Andres' name is listed as 
`Plazas Malagón,Andrés,A.~A.~Plazas,...`
* The rest are issues with blanck affiliations that are related to institutions not in the DES database.

If I edit your order file to correct the entries for Bonnett and Plazas, then I get the expected output.

**Comment by pmelchior** [comment]
OK, that makes sense. But I haven't seen any warnings when I ran the script.

**Comment by kadrlica** [comment]
Yeah, they weren't printed on older versions of the script (and were added for exactly this reason). I'm in the process of building a new release. I'd recommend grabbing it at the end of the week.

**Comment by pmelchior** [comment]
Good. I don't mind problems (especially when I caused some of them with a typo) as long am I'm informed about them.
