### ISSUE TITLE
Support for A&A formatting

### ISSUE THREAD

**Issue by kadrlica** [DarkEnergySurvey/mkauthlist#17]
The [A&A author list formatting](https://www.aanda.org/author-information/latex-issues/the-manuscript-header) looks like a headache. It is fundamentally different from the revtex formatting used by PhysRev and ApJ. It may be similar enough to the formatting by MNRAS to hack that to work, but does not look trivial.

**Comment by kadrlica** [comment]
This probably won't be done until someone requests it.

**Comment by BrunoSanchez** [comment]
I have created the patch for A&A. Will be asking for a pull request soon.

**Comment by BrunoSanchez** [comment]
Pull request with patch for A&A is #39

**Comment by kadrlica** [comment]
Closed by #39
