### ISSUE TITLE
Remove numpy dependency

### ISSUE THREAD

**Issue by brianv0** [DarkEnergySurvey/mkauthlist#18]
Can we work on removing the numpy dependency?

For the hack sort (i.e. "da Costa"), can we just do a lowercase, locale-aware sort of all names?

**Comment by kadrlica** [comment]
I am not opposed to removing numpy, but I'd rather not mess with something that works. That said, I think this is at least partially covered by [test_authlist.py](https://github.com/DarkEnergySurvey/mkauthlist/blob/master/tests/test_authlist.py)

I've made a new issue (#19) to track the lowercase hack sort, which is really a database issue, not a mkauthlist issue.

**Comment by kadrlica** [comment]
I don't think we are going to want to remove the numpy dependency. If anything, I'm thinking about moving to use pandas, which would upstream a lot of the details of the csv parsing (which I don't want to maintain) and could lead to much cleaner author affiliation lists using pandas `groupby`.
