### ISSUE TITLE
Enable contribution statements for LSST DESC

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergySurvey/mkauthlist#3]
The LSST DESC will collect and store short contribution statements for each author of each journal paper it writes; these statements will be presented in the acknowledgements. Here are some things to do, we may need to add (and perhaps issue) more:

* [x]  Make sure `mkauthlist` can process the [`authors.csv` file provided by the DESC `start_paper` cookiecutter](https://github.com/DarkEnergyScienceCollaboration/start_paper/blob/issue/25/mkauthlist/%7B%7Bcookiecutter.folder_name%7D%7D/authors.csv)
* [x] If a suitable option is passed in, produce a file called `contributions.tex` that can be `\input` into the acknowledgments section. These statements should be of the form "$FirstName $LastName $Contribution."  We might want to use $AuthorInitials instead of the names - this seems to be the standard way to refer to authors in most journals, but let's start with using names. We should lowercase the first character of the $Contribution, just to make sure. The contributions should appear in the same order as the authors.

**Comment by kadrlica** [comment]
I've made some initial progress on this. The first item above was already implemented. For the second item, I've chosen to format the contributions as one-per-line using `$Authorname` and capitalized `$Contribution`. For example, the content of `contributions.tex` looks like:
```
Author contributions are listed below. \\
A.~Drlica-Wagner: Code monkey \\
P.~Marshall: Motivation \\
S.~Digel: Wisdom \\
```
